apiVersion: apps/v1
kind: Deployment 
metadata:
  name: zomato
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zomato
  template:
    metadata:
      labels:
        app: zomato
    spec:
      containers:
        - name: zomato
          image: 727646465604.dkr.ecr.us-east-1.amazonaws.com/zomato-repo:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: zomato
spec:
  selector:
    app: zomato
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer