# create deployment.yaml file
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zomato
spec:
  replicas: 2
  selector:
    matchLabels:
      app: zomato
  template:
    metadata:
      labels:
        app: zomato
    spec:
      containers:
      - name: zomato
        image: 727646465604.dkr.ecr.us-east-1.amazonaws.com/zomato-repo:latest
        ports:
        - containerPort: 3000

