apiVersion: apps/v1
kind: Deployment
metadata:
  name: zomato
  labels:
    app: zomato
spec:
  replicas: 2
  selector:
    matchLabels:
      app: zomato
  template:
    metadata:
      labels:
        app: zomato
    spec:
      containers:
      - name: zomato
<<<<<<< HEAD
        image:727646465604.dkr.ecr.us-east-1.amazonaws.com/zomato-repo:latest
=======
        image: kastrov/zomato:latest
>>>>>>> 94acad9399cc0c677fc1ebf25f98e1b1973d2123
        ports:
        - containerPort: 3000
